on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '11'
          cache: 'gradle'
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - uses: pnpm/action-setup@v2
      - run: |
          ./gradlew build --no-daemon
          echo "gradle.publish.key=$GRADLE_PUBLISH_KEY" > ~/.gradle/gradle.properties
          echo "gradle.publish.secret=$GRADLE_PUBLISH_SECRET" >> ~/.gradle/gradle.properties
          pnpm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: plugin/build/reports
